import { Topic } from '@/types'

export const TOPICS: Topic[] = [
  {
    id: 1,
    name: 'C Programming',
    icon: 'code',
    subtopics: [
      'Basic structure of C program',
      'Data types, variables and constants',
      'Operators (arithmetic, relational, logical, bitwise)',
      'Input / output (scanf, printf)',
      'Control statements (if, if-else, switch)',
      'Loops (for, while, do-while)',
      'Arrays (1D, 2D)',
      'Strings and character array',
      'Functions (user defined, library)',
      'Pointer and pointer arithmetic',
      'Structures and union',
      'File handling',
      'Preprocessor directives',
      'Dynamic memory allocation (malloc, calloc, realloc, free)',
    ],
  },
  {
    id: 2,
    name: 'OOP',
    icon: 'layers',
    subtopics: [
      'Class and object',
      'Abstraction',
      'Encapsulation',
      'Inheritance (single, multilevel, multiple, hierarchical, hybrid)',
      'Polymorphism (compile time and run time)',
      'Constructor and destructor',
      'Access modifiers (public, private, protected)',
      'Function overloading and overriding',
      'Virtual function and dynamic binding',
      'Operator overloading',
      'Friend function and class',
      'Static members and methods',
      'File handling in C++',
      'Templates and exception handling (basic)',
    ],
  },
  {
    id: 3,
    name: 'Data Structures & Algorithm',
    icon: 'git-merge',
    subtopics: [
      'Arrays',
      'Linked list (singly, doubly, circular)',
      'Stack (array and linked list implementation)',
      'Queue (linear, circular, priority queue)',
      'Deque',
      'Tree (binary tree, BST, traversals)',
      'Binary search tree (insert, delete, search)',
      'Heap (min heap, max heap)',
      'Graph (BFS, DFS, representation)',
      'Hashing (hash function, collision handling)',
      'Sorting algorithms (bubble, selection, insertion, merge, quick, heap, counting, radix)',
      'Searching algorithms (linear, binary search)',
      'Recursion',
      'Time and space complexity (Big-O notation)',
    ],
  },
  {
    id: 4,
    name: 'Data Communication',
    icon: 'radio',
    subtopics: [
      'Components of data communication',
      'Data representation (analog, digital)',
      'Transmission modes (simplex, half, full duplex)',
      'Transmission media (guided and unguided)',
      'Multiplexing (FDM, TDM, WDM, CDM)',
      'Switching techniques (circuit, packet, message)',
      'Error detection (parity, checksum, CRC)',
      'Error correction (Hamming code)',
      'Flow control (stop-and-wait, sliding window)',
      'Data link control (LLC, MAC sublayer)',
      'LAN technologies (Ethernet, Wi-Fi)',
      'Network topologies (bus, star, ring, mesh)',
    ],
  },
  {
    id: 5,
    name: 'Computer Networking',
    icon: 'network',
    subtopics: [
      'OSI model (7 layers)',
      'TCP/IP model and protocol suite',
      'Physical layer concepts',
      'Data link layer (framing, MAC, ARQ)',
      'Network layer (IP, subnetting, CIDR)',
      'Transport layer (TCP, UDP)',
      'Application layer (HTTP, FTP, SMTP, DNS)',
      'IP addressing (IPv4, IPv6)',
      'Subnetting and supernetting',
      'Routing protocols (RIP, OSPF, BGP)',
      'Network devices (hub, switch, router, bridge, gateway)',
      'LAN, MAN, WAN',
      'Wireless networks (Wi-Fi, Bluetooth)',
      'DNS, DHCP, NAT',
      'Network security basics (firewall, VPN)',
    ],
  },
  {
    id: 6,
    name: 'Database Management System',
    icon: 'database',
    subtopics: [
      'DBMS concepts and architecture',
      'ER model and diagram',
      'Relational model and keys (primary, foreign, candidate)',
      'Normalization (1NF, 2NF, 3NF, BCNF)',
      'SQL basics (DDL, DML, DCL, TCL)',
      'SQL queries (SELECT, JOIN, GROUP BY, HAVING, ORDER BY)',
      'Set operations',
      'Views',
      'Transactions and ACID properties',
      'Concurrency control',
      'Indexing',
      'Backup and recovery',
    ],
  },
  {
    id: 7,
    name: 'Artificial Intelligence',
    icon: 'cpu',
    subtopics: [
      'AI concepts and techniques',
      'Agents and environments',
      'Problem solving search strategies (BFS, DFS, UCS, greedy, A*)',
      'Knowledge representation (logical, rules, ontology)',
      'Inference techniques (forward chaining, backward chaining)',
      'Expert systems (structure, components)',
      'AI applications (NLP, computer vision, robotics)',
      'Uncertainty in AI (probability basics, Bayesian networks)',
      'Constraint satisfaction problems (CSP)',
    ],
  },
  {
    id: 8,
    name: 'Machine Learning',
    icon: 'trending-up',
    subtopics: [
      'Types of ML (supervised, unsupervised, reinforcement)',
      'Supervised learning algorithms (linear regression, logistic regression, SVM, decision tree, random forest, k-NN, naive Bayes)',
      'Unsupervised learning algorithms (K-means, hierarchical clustering, PCA)',
      'Model evaluation (accuracy, precision, recall, F1-score, ROC-AUC)',
      'Bias-variance and underfitting/overfitting',
      'Feature engineering and selection',
      'Cross validation (K-fold)',
      'Regularization (L1, L2)',
      'Hyperparameter tuning (grid, random search)',
    ],
  },
  {
    id: 9,
    name: 'Data Center',
    icon: 'server',
    subtopics: [
      'Data center concepts and architecture',
      'Data center tiers (tier I, II, III, IV)',
      'Components (rack, server, storage, cooling, power, UPS, PDU)',
      'Redundancy (N, N+1, 2N)',
      'Hot aisle vs cold aisle',
      'RAID levels (0, 1, 5, 6, 10)',
      'Virtualization and hypervisor (type 1, type 2)',
      'Storage technologies (SAN, NAS, DAS)',
      'Backup types (full, incremental, differential)',
      'Disaster recovery (RPO, RTO)',
      'High availability vs fault tolerance',
      'Green data center and energy efficiency',
    ],
  },
  {
    id: 10,
    name: 'Operating System',
    icon: 'monitor',
    subtopics: [
      'OS concepts and functions',
      'Process management and scheduling (FCFS, SJF, priority, round robin)',
      'Synchronization (semaphore, mutex, monitor)',
      'Deadlock (conditions, prevention, avoidance, detection)',
      'Memory management (paging, segmentation, virtual memory)',
      'File system (allocation methods, directory structure)',
      'I/O management and device management',
    ],
  },
  {
    id: 11,
    name: 'Software Engineering',
    icon: 'git-branch',
    subtopics: [
      'SDLC (waterfall, agile, iterative, spiral)',
      'Requirement engineering',
      'UML diagrams (use case, class, sequence, activity, ER)',
      'System design (DFD, modular design)',
      'Software testing (unit, integration, system, UAT)',
      'Black box and white box testing',
      'Maintenance types (corrective, adaptive, perfective, preventive)',
      'Project management (estimation, scheduling)',
      'Agile methodology (Scrum, Kanban)',
    ],
  },
  {
    id: 12,
    name: 'Cyber Security',
    icon: 'shield',
    subtopics: [
      'CIA triad (confidentiality, integrity, availability)',
      'Authentication and authorization',
      'Cryptography basics (symmetric, asymmetric)',
      'Hashing and digital signature',
      'SSL/TLS, HTTPS',
      'Firewalls, IDS, IPS',
      'Malware, virus, phishing, ransomware',
      'Network security (VPN, WPA, WPA2, WPA3)',
      'Common attacks (DoS, SQL injection, XSS, man-in-the-middle)',
    ],
  },
  {
    id: 13,
    name: 'Important Concepts & Math',
    icon: 'hash',
    subtopics: [
      'Number system (binary, octal, hexadecimal)',
      'Boolean algebra and logic gates',
      'Combinatorics (permutation, combination)',
      'Set theory',
      'Probability and statistics basics',
      'Logic and propositional logic',
      'Discrete mathematics basics',
      'Time and space complexity (Big-O notation)',
      'Matrices and linear equations (basics)',
      'Number theory basics',
    ],
  },
  {
    id: 14,
    name: 'ICT & Emerging Technologies',
    icon: 'zap',
    subtopics: [
      'Internet of things (IoT)',
      'Cloud computing (IaaS, PaaS, SaaS)',
      'Big data and data analytics',
      'Blockchain technology',
      '5G technology',
      'Artificial intelligence applications',
      'E-government services in Bangladesh',
      'ICT trends and emerging technologies',
    ],
  },
]
